version: '2'

services:
  web:
    build: 
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - /.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    ports:
      - 5482:5432  
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=projdb

volumes:
  postgres_data: